---
language: ruby
bundler_args: --without development acceptance integration
cache: bundler
before_install: rm Gemfile.lock || true
sudo: false
script: bundle exec rake test
matrix:
  - rvm: 2.3.1
    env: PUPPET_GEM_VERSION="~> 4.2.0"
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 4.2.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 4.2.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.8.0" FUTURE_PARSER=yes
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.8.0"
